version: '3'

networks:
  monitor:
    driver: bridge

services:
  mysql:
    image: hong0220/hong-mysql:0.0.1
    container_name: mysql
    hostname: mysql
#    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql"
      - "TZ=Asia/Shanghai"
    ports:
      - '3306:3306'
    networks:
      - monitor
