version: '3'

networks:
  monitor:
    driver: bridge

services:
  mysql:
    image: hong0220/hong-mysql:0.0.1
    container_name: mysql
#    restart: always
    ports:
      - '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql"
      - "TZ=Asia/Shanghai"
    volumes:
      - /Users/hongduoduo/Desktop/soft/mysql/data:/var/lib/mysql
    networks:
      - monitor

  nacos:
    image: nacos/nacos-server:1.1.4
    container_name: nacos
#    restart: always
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - MYSQL_DATABASE_NUM=1
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=mysql
    volumes:
      - /Users/hongduoduo/Desktop/soft/nacos/logs:/home/nacos/logs
    networks:
      - monitor

  sentinel:
    image: bladex/sentinel-dashboard:1.7.2
    container_name: sentinel
#    restart: always
    ports:
      - "8858:8858"
    networks:
      - monitor
