version: '3'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: hong0220/hong-prometheus:0.0.1
    container_name: prometheus
    hostname: prometheus
#    restart: always
#    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  alertmanager:
    image: hong0220/hong-alertmanager:0.0.1
    container_name: alertmanager
    hostname: alertmanager
#    restart: always
    ports:
      - "9093:9093"
    networks:
      - monitor

  grafana:
    image: hong0220/hong-grafana:0.0.1
    container_name: grafana
    hostname: grafana
#    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor

  # 机器监控信息收集器
  node-exporter:
    image: hong0220/hong-node-exporter:0.0.1
    container_name: node-exporter
    hostname: node-exporter
#    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitor

  # 容器监控
  cadvisor:
    image: hong0220/hong-cadvisor:0.0.1
    container_name: cadvisor
    hostname: cadvisor
#    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitor

  # mysql
  mysql:
    image: hong0220/hong-mysql:0.0.1
    container_name: mysql
    hostname: mysql
#    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql"
      - "TZ=Asia/Shanghai"
    ports:
      - '3306:3306'
    networks:
      - monitor

  mysqld-exporter:
    image: hong0220/hong-mysqld-exporter:0.0.1
    container_name: mysqld-exporter
    hostname: mysqld-exporter
#    restart: always
    ports:
      - "9104:9104"
    # 被监控的mysql
    environment:
      DATA_SOURCE_NAME: "root:mysql@(192.168.0.101:3306)/"
    networks:
      - monitor
