version: '3'

networks:
  monitor:
    driver: bridge

services:
  consul:
    image: hong0220/hong-consul:0.0.1
    container_name: consul
    hostname: consul
#    restart: always
#    volumes:
#      - ./consul/data:/consul/data
#      - ./consul/config:/consul/config
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -node=consul_Server1 -bootstrap-expect=1 -ui
    networks:
      - monitor
