version: '3'

networks:
  monitor:
    driver: bridge

services:
#  jenkins:
#    # 拉取远程制作镜像
#    image: hong0220/hong-jenkins:0.0.2
#    container_name: jenkins
#    hostname: jenkins
##    restart: always
#    ports:
#      - '8080:8080'
##    volumes:
##      - ./jenkins/data/:/var/jenkins_home
#    networks:
#      - monitor

#  # ssh root@192.168.0.101 -p 2222
#  centos:
#    image: hong0220/hong-centos:0.0.1
#    container_name: centos
#    hostname: centos
##    restart: always
#    ports:
#      - '2222:22'
#      - '8090:22'
#    networks:
#      - monitor

  gitlab:
    image: gitclub/gitlab-ce-zh:10.0.6
    container_name: gitlab
    hostname: gitlab
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.163.com"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = "xxx@163.com"
        gitlab_rails['smtp_password'] = "xxx"
        gitlab_rails['smtp_domain'] = "163.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'xxx@163.com'
        gitlab_rails['git_user_email'] = 'xxx@163.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - '9999:80'
#      - '8443:443'
#      - '822:22'
    volumes:
      - /Users/hongduoduo/Desktop/soft/gitlab/config:/etc/gitlab
      - /Users/hongduoduo/Desktop/soft/gitlab/data:/var/opt/gitlab
      - /Users/hongduoduo/Desktop/soft/gitlab/logs:/var/log/gitlab